/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.funfun.redbook;

class Application {
    public static void main(String[] args) {
        FPList<String> consList = FPList.fpList("a", "b", "c", "d");
        System.out.println("hello? consList? " + consList);
        FPList<Integer> consList2 = FPList.fpList(1, 2, 3, 4);
        System.out.println("consList.map { + 1} " + consList2.map((Integer num) -> num + 1));
    }
}
