/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.funfun.redbook

class Application {
    public static void main(String[] args) {
        System.out.println("Hello Java");
    }
}
